<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerILxGOvG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerILxGOvG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerILxGOvG.legacy');
=======
if (\class_exists(\ContainerA3SbuvE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA3SbuvE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA3SbuvE.legacy');
>>>>>>> master

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerILxGOvG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerILxGOvG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ILxGOvG',
    'container.build_id' => '27c13524',
    'container.build_time' => 1553783914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerILxGOvG');
=======
    \class_alias(\ContainerA3SbuvE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA3SbuvE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A3SbuvE',
    'container.build_id' => '064e1b0d',
    'container.build_time' => 1553779659,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA3SbuvE');
>>>>>>> master
