<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOcv7ahC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOcv7ahC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOcv7ahC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOcv7ahC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOcv7ahC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ocv7ahC',
    'container.build_id' => '0c9a78ac',
    'container.build_time' => 1554106967,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOcv7ahC');
