<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerILxGOvG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerILxGOvG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerILxGOvG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerILxGOvG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerILxGOvG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ILxGOvG',
    'container.build_id' => '27c13524',
    'container.build_time' => 1553783914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerILxGOvG');
